### ISSUE TITLE
fluxgui will not start if old ppidfile is present

### ISSUE THREAD

**Issue by schorsch3000** [xflux-gui/xflux-gui#1]
Hi, i'm using fluxgui 1.1.8.
sometimes on shutdown fluxgui issn't able to remove it's pid-file, which wiredly lays in /tmp.
But that shouldn't matter since it is a pid-file, not a lock-file, but fluxgui uses it as a lockfile, it will not start if that file is present, even if there is no process with the pid in the pid-file:
```
$ cat /tmp/fluxgui_dicky.pid
19170 $(cat /tmp/fluxgui_dicky.pid)
  PID TTY      STAT   TIME COMMAND
$ fluxgui 
fluxgui is already running, exiting
$ rm /tmp/flux*
$ fluxgui 

```

imo should fluxgui check if there is a process with the id in the pid-fileand should check if that process is indeed a fluxgui.

Are there some information on how to build? if so, i might have a look into the source and maybe send a pullrequest addressing this...

**Comment by Kilian** [comment]
You are right, it does function as a lock file currently.

Running should work with "python src/fluxgui/" provided you have xflux in your path. The PID file function is here: https://github.com/xflux-gui/xflux-gui/blob/master/src/fluxgui/fluxapp.py#L55 and is pretty self-contained, so would make for a nice pull request :)

**Comment by schorsch3000** [comment]
i can't get the code here up and running, but i might have spot some thing.
to check if a process with the old PID exist you use:

    ps -q %i -o comm= | grep -i python > /dev/null

neither the ps on my linux-machine nor the ps at my work-mac knows about a -q switch...

couldn't you just use 

    ps %i

instead of ps -q %i -o comm= 

we also can simplify the grep part:

    ps %i | grep -iq python

-q writes nothing to stderr, just set an errorcode.

but having ps -q exit with an errorcode not 0 would mean it will never refuse to start, even if there is a process running.

Knowing that i inspected the code installed from the deb.

That's not the same code!

my first few lines of /usr/lib/pymodules/python2.7/fluxgui/fluxgui.py 
looks like:

#!/usr/bin/python
    import appindicator
    import gtk
    import gtk.glade
    import gconf
    import sys
    import pexpect
    import os
    from xdg.DesktopEntry import DesktopEntry
    
    VERSION = "1.1.8"
    
    
    class Fluxgui:
        def __init__(self):
            self.check_pid()
            self.indicator = Indicator(self)
    
            self.color = None;
            self.settings = Settings(self)
            self.start_xflux(self.settings.latitude, self.settings.longitude,
                             self.settings.zipcode, self.settings.color)
    
            if self.settings.latitude is "" and self.settings.zipcode is "":
                self.open_preferences("activate")
    
        def check_pid(self):
            pid = str(os.getpid())
            self.pidfile = "/tmp/fluxgui_%s.pid" % os.environ['USER']
    
            if os.path.isfile(self.pidfile):
                print "fluxgui is already running, exiting"
                sys.exit()
            else:
                file(self.pidfile, 'w').write(pid)


That package is from:

deb http://ppa.launchpad.net/kilian/f.lux/ubuntu trusty main

i am confused?!

**Comment by Darcidride** [comment]
Hi,
First thank you for your work on this tool.

I encounter the same error as above :
![](http://i.imgur.com/36DwBpY.png)

Package fluxgui from :
deb http://ppa.launchpad.net/nathan-renniewaldock/flux/ubuntu xenial main 
deb-src http://ppa.launchpad.net/nathan-renniewaldock/flux/ubuntu xenial main 

My computer :
![](http://i.imgur.com/sWD9kLx.png)
