### ISSUE TITLE
Does not work on Debian Buster

### ISSUE THREAD

**Issue by theAkito** [xflux-gui/xflux-gui#110]
I just installed this app manually from master. Unfortunately, python-appindicator depends on `libappindicator1 (= 0.4.92-4)` but Debian Buster has only `libappindicator1 (= 0.4.92-7)` to offer. Other programs already depend on the new version and I don't want to replace this package with the older one, making all the other programs uninstall just to make this one work.

**Comment by Akito13** [comment]
> 
> 
> We don't have any control over the dependencies of `python-appindicator`, so I'm not sure what kind of fix you have in mind. Also, we just ported to GTK+ 3 in #112, so maybe the dependencies are different now (I'm honestly not sure what the deps are now, I just now they're some subset of the packages I have installed ...).
> 
> Closing this as I don't think it's actionable, but let me know if I misunderstood.

The main reason I opened the issue is to inform the developers, as it might interest them what issues may happen. It's not a big issue for me.

> Also, we just ported to GTK+ 3 in #112

But I might try it out again.
