### ISSUE TITLE
Typo in postinst script

### ISSUE THREAD

**Issue by jemekite** [xflux-gui/xflux-gui#21]
There is a typo in postinstall script causing this error:
```
Setting up fluxgui (1.1.9~20160807-g6de5c65-1~xenial) ...
/var/lib/dpkg/info/fluxgui.postinst: 1: /var/lib/dpkg/info/fluxgui.postinst: n#!/bin/sh: not found
```

File: https://github.com/xflux-gui/xflux-gui/blob/master/debian/postinst#L1

`n#!/bin/sh`

**Comment by ntc2** [comment]
My fault :P Thanks for the report and fix!
