### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by Thamaraiselvam** [xflux-gui/xflux-gui#28]
/usr/local/lib/python2.7/dist-packages/fluxgui/fluxapp.py:75: GtkWarning: Cannot transform xsetting Net/IconThemeName of type gchararray to type GdkColor

  gtk.gdk.screen_get_default().get_setting('gtk-icon-theme-name')
/usr/local/lib/python2.7/dist-packages/fluxgui/fluxapp.py:75: GtkWarning: Cannot transform xsetting Net/IconThemeName of type gchararray to type gint

  gtk.gdk.screen_get_default().get_setting('gtk-icon-theme-name')

**Comment by holocronweaver** [comment]
Please describe your system and the exact problem you are experiencing.

Is #27 by any chance related?

**Comment by kulicuu** [comment]
Same here.  New kernel.  Ubuntu.  Same as #27

**Comment by ntc2** [comment]
Sounds like this is a duplicate of #27.
