### ISSUE TITLE
No icon in Cinnamon

### ISSUE THREAD

**Issue by mioux** [xflux-gui/xflux-gui#29]
I have many desktops in my office. All are on Debian 8.5

Each user has it's own desktop configuration.

No problem with Mate, not tested with Gnome

On the other hand, when running Cinnamon, there is no icon in taskbar

**Comment by ntc2** [comment]
No idea how to trouble shoot this.

**Comment by itsabear** [comment]
How do you install xflux-gui?

**Comment by mioux** [comment]
I have cloned the repo, then builded deb from source, copied the same deb on all the machines, then `dpkg -i debfile.deb` then `apt -y install` for missing dependencies, and runned gui.

**Comment by Pandiora** [comment]
I had the same problem, but I followed your installation-instructions. Turns out that I had to restart and the app was running from cmd btw. Also added it to autostart and it works like a charm. Thank you! Theres also a command to refresh the icons but I can't remember it. Maybe a restart will do it for you too @mioux

**Comment by theblackhole** [comment]
If I start fluxgui via the terminal I get these warning messages. I don't know if it's useful :

```
/usr/lib/python2.7/dist-packages/fluxgui/fluxapp.py:75: GtkWarning: Cannot transform xsetting Net/IconThemeName of type gchararray to type GdkColor

  gtk.gdk.screen_get_default().get_setting('gtk-icon-theme-name')
/usr/lib/python2.7/dist-packages/fluxgui/fluxapp.py:75: GtkWarning: Cannot transform xsetting Net/IconThemeName of type gchararray to type gint

  gtk.gdk.screen_get_default().get_setting('gtk-icon-theme-name')
```
 
_fluxgui 1.1.9~20160808-g4125e70-1~xenial
Linux Mint 18 Cinnamon x64_

**Comment by Pandiora** [comment]
@theblackhole You should open another issue, because your problem looks like something else?!
Otherwise a short search will bring up this: https://github.com/Kilian/f.lux-indicator-applet/issues/33

Maybe you can troubleshoot your problem this way. There are a lot solutions in this thread.

**Comment by drcross** [comment]
Just to pipe in here, yeah on the latest version of Mint (18) which uses Cinnamon, when you initially install xflux-gui the icon does not appear on the taskbar until after a restart. Here is an example- 
![flux2](https://cloud.githubusercontent.com/assets/3392505/20245943/05e2a244-a9a4-11e6-9efc-bc995fbd0cff.png)
![flux](https://cloud.githubusercontent.com/assets/3392505/20245944/05e40378-a9a4-11e6-944b-121f1a0ccf66.png)

**Comment by Kilian** [comment]
This, I think, has to do with your desktop environment maintaining a cache of app icons, and ours simply not having loaded yet right after installation. I don't know enough about icon loading in cinnamon to provide any additional insights though.

**Comment by ntc2** [comment]
Sounds like the solution is to restart your computer / this is a one-off issue.
