### ISSUE TITLE
fluxgui failed to run

### ISSUE THREAD

**Issue by omerasif57** [xflux-gui/xflux-gui#31]
Hi,
After installing, `fluxgui` prompts the following:
`/usr/local/bin/fluxgui: line 1: fg: no job control`
`/usr/local/bin/fluxgui: line 2: syntax error near unexpected token 'ImageMagick'`
`/usr/local/bin/fluxgui: line 2: %%Creator: (ImageMagick)'`

I am using **Ubuntu 16.04 LTS**

**Comment by ntc2** [comment]
This looks like you somehow overwrote the contents of your `/usr/local/bin/fluxgui` file: there is no use of ImageMagick in fluxgui. Closing this assuming it's a weird, one-off problem.
