### ISSUE TITLE
Less downloading is possible for installation in git clone.

### ISSUE THREAD

**Issue by alisharpasand** [xflux-gui/xflux-gui#33]
Adding --depth=1 will just download the latest revision and not the whole commit history and makes the installation process a lot faster.

**Comment by ntc2** [comment]
There aren't many commits (< 200) and the repo is small (< 4MB), so I don't think adding this possibility to the README is worthwhile. I don't want to suggest it as the default because I expect this will just get in the way of people that want to submit pull requests.
