### ISSUE TITLE
Reset screen color on close

### ISSUE THREAD

**Issue by theblackhole** [xflux-gui/xflux-gui#35]
Currently, if you close fluxgui, the color won't reset to original.

_fluxgui 1.1.9~20160808-g4125e70-1~xenial_
_Linux Mint 18 Cinnamon x64_

**Comment by simmel** [comment]
This can be closed in favour of #34.

**Comment by ntc2** [comment]
@theblackhole, are you saying that the screen remains red shifted after you close fluxgui? If yes, then this doesn't sound related to #34.

**Comment by theblackhole** [comment]
Exactly @ntc2 , it's not related to #34 : I don't know if it's a bug or if it's just not implemented yet but in Windows, when you close f.lux, the screen reset to the default color temp. That's not the case here : it remains red shifted.

**Comment by ntc2** [comment]
I just verified that I have this problem on my system too (Ubuntu 16.04). As a workaround, you can pause flux before choosing "quit".
