### ISSUE TITLE
Homepage appears to be outdated

### ISSUE THREAD

**Issue by ShalokShalom** [xflux-gui/xflux-gui#42]
The old homepage post from 2010 suggest, that the project is unmaintained since then.

**Comment by ntc2** [comment]
What homepage?

**Comment by ShalokShalom** [comment]
https://justgetflux.com/linux.html

**Comment by Kilian** [comment]
Pinging @herf. IMHO that page is fine: it links to the right things and is up to date. It does say "2010" on top of the page and that could be confusing though.

**Comment by ShalokShalom** [comment]
My initial reaction was: 

Gnah, unmaintained project.

I did a research for its source code, since i hope for a fork and something.

**Comment by herf** [comment]
fixed!
