### ISSUE TITLE
Requirements.txt?

### ISSUE THREAD

**Issue by nickmarton** [xflux-gui/xflux-gui#44]
A `setup/requirements.txt` would be beneficial; had to search through pip and synaptic to meet all the dependencies.

**Comment by Kilian** [comment]
A requirements.txt sounds nice but it doesn't allow you to install non-python dependencies. 

We have all dependencies listed in the readme for setup instructions as well as in the debian setup file: https://github.com/xflux-gui/xflux-gui/blob/master/debian/control so whilst for python-only projects getting all dependencies via pip works fine, that's not really the case here.

**Comment by nickmarton** [comment]
Ah I didn't see the debian setup file, my apologies!
