### ISSUE TITLE
Add versioned tarball release

### ISSUE THREAD

**Issue by baimafeima** [xflux-gui/xflux-gui#45]
Could you add a versioned tarball release here on GitHub?

**Comment by baimafeima** [comment]
Thank you for considering a GitHub release. Any updates on this yet?

**Comment by ntc2** [comment]
No updates.

**Comment by ntc2** [comment]
But it's probably about time for another release. Need to figure out a process for getting the PPA updated accordingly.

**Comment by Kilian** [comment]
If we start doing github releases, it might make it easier for other automation (ie other repositories) to pick those up. @baimafeima other than an easy way to download, what would a versioned tarbal bring you?

**Comment by baimafeima** [comment]
The fact that it could be packaged and distributed by maintainers such as here: https://solus-project.com/articles/packaging/request-a-package/en/

**Comment by baimafeima** [comment]
> But it's probably about time for another release. Need to figure out a process for getting the PPA updated accordingly.
I think PPAs are a waste of effort. They only work on Ubuntu-based systems. Why not release versioned tarballs so distribution maintainers can actually evaluate your software for possible inclusion into core repositories (for easy distribution to end users) and an additional cross-platform release such as Flatpak for end-users? http://flatpak.org/

**Comment by ntc2** [comment]
Was hoping that https://github.com/xflux-gui/xflux-gui/issues/48 would land, but seems that's dead in the water. I just tagged a v1.1.10 release, so closing this issue.
