### ISSUE TITLE
flux for ubuntu xenial (16.04)

### ISSUE THREAD

**Issue by yogesum** [xflux-gui/xflux-gui#5]
I have used `f.lux` for ubuntu in previous versions. Latest LTS release was yesterday and there is no release.

**Comment by stefansundin** [comment]
I got it running by running the commands in the readme. Wish there was a proper package though.

**Comment by 23Skidoo** [comment]
@stefansundin There is an unofficial PPA: 

http://ubuntuhandbook.org/index.php/2016/03/install-f-lux-in-ubuntu-16-04/
https://launchpad.net/~nathan-renniewaldock/+archive/ubuntu/flux

**Comment by ntc2** [comment]
@23Skidoo Thanks! I updated the README with your links.
