### ISSUE TITLE
Collapsing the the gnome3 tray disables context menu

### ISSUE THREAD

**Issue by feanor12** [xflux-gui/xflux-gui#50]
Steps:
1.  start fluxgui
2.  right click on the tray icon to get the menu -> works if tray was not collapsed
3.  collapse tray and reopen
4.  right click on flux tray icon -> nothing

**Comment by ntc2** [comment]
@feanor12 , I'm unable to reproduce this.

1. What do you mean by "collapse the tray and reopen"? I tried "right click on Gnome tray -> properties -> show hide button", and then used the hide button to collapse the tray and reopen, but didn't experience any issue with fluxgui. Here's a picture of the "hide button": 
![gnome-tray](https://cloud.githubusercontent.com/assets/16421/23171100/69fd8e28-f806-11e6-910c-570852bcd054.png)


2. How did you install fluxgui? If you are not using the latest version downloaded here from GitHub (it's very easy to install, see the README), please try that and see if your problem persists.

**Comment by ntc2** [comment]
Haven't heard back so I'm assuming this is not a priority.
