### ISSUE TITLE
ImportError

### ISSUE THREAD

**Issue by ffoodd** [xflux-gui/xflux-gui#56]
Hi there,

Didn't find any issue speaking of this: I just made a manual install (globally) on Ubuntu 16.04. `xflux` works as intended (seeing the `Welcome to xflux` etc.).

I followed the README to install **fluxgui**, but when trying to run I get this message:
```
Traceback (most recent call last):
  File "/usr/local/bin/fluxgui", line 17, in <module>
    from fluxgui.fluxapp import main
ImportError: cannot import name main
```
I suppose something wen wrong when installing but I didn't get any error nor warning.

Any idea?

**Comment by acoret** [comment]
i think u used apt to install.if not,please check if essential library installed.and make sure you are working with pyhton2,then,you need make path right,as you see,fluxgui is trying import main in the path $pwd.In fact...flux doesn't work on my computer,it started,and no error report,but just not work.(it work before).Now i use redshift.(archlinux it was complied by commuity).Dont know what happen

**Comment by ntc2** [comment]
@ffoodd, based on the error message you're seeing, the import of the module `fluxgui.fluxapp` succeeded, but there was no `main` in that module! This makes me think you have multiple versions of fluxgui installed, and `/usr/local/bin/fluxgui` is a newer than the `fluxgui.fluxapp` that it's importing. To verify this you could figure out which file `fluxgui.fluxapp` is coming from: just add
```python
print fluxgui.fluxapp.__file__
```
to `/usr/local/bin/fluxgui` below the `from fluxgui.fluxapp import main` line. That will probably point you to a `.pyc` file, and if you look at the corresponding `.py` file (i.e. the file with the same name, except replacing `.pyc` with `.py`), you'll probably see that it doesn't contain a `main`.

But how to fix the problem: delete all the fluxgui related files you have and then reinstall. You should be able to find all (most?) of them using `locate flux` or `find / -name '*flux*'`. That list may include some files unrelated to fluxgui that just happen to have flux in their names, so don't delete those!

Let me know if this helps.
