### ISSUE TITLE
How to set the 'slow' transition speed?

### ISSUE THREAD

**Issue by HoldYourWaffle** [xflux-gui/xflux-gui#57]
Have been using f.lux for quite a while on windows where I had a nice slow-paced transition from day to night mode. However I can't seem to find this option in the linux-gui.

Is this still possible (either via gui or terminal) and how?

**Comment by ntc2** [comment]
I believe this is not possible, but the command line Linux f.lux program, `xflux`, is poorly documented so it's hard to be sure. Perhaps @herf knows?

**Comment by ntc2** [comment]
Going to assume this isn't possible with `xflux`, which we use to actually change the screen color. The RedShift docs indicate that it might support this feature (it says it transitions "slowly"): http://jonls.dk/redshift/.
