### ISSUE TITLE
Does not work on Ubuntu 17.04

### ISSUE THREAD

**Issue by izznogooood** [xflux-gui/xflux-gui#58]
Doesnt work on Ubuntu 17.04 (PPA).

Seems fine, but screen unchanged.

**Comment by ntc2** [comment]
What doesn't work? Please describe symptoms. Thanks!

**Comment by izznogooood** [comment]
I'm sorry, but there's really no other way to put it. Everything seems fine, it just wont change the color temp. Even when I manually press Preview. Other than that, the app looks and feels perfectly ok.

**Comment by hedgecrog** [comment]
I can confirm this in my system too - f.lux doesn't change any color temp on 17.04 even when trying manually by using above mentioned preview button

**Comment by ntc2** [comment]
@izznogooood , thanks for explaining. Actually, what you said is very helpful! Note that "does not work" could mean lots of things, e.g.

- failed to install
- no errors during install but it crashes when you run it
- it appears to run fine, but doesn't change screen color

Sounds like you're having the last problem. Are you experiencing Issue #27 by any chance?

**Comment by izznogooood** [comment]
I'm not sure but this has no effect:

`anders@yoga:~/Downloads/flux$ ./xflux12 -l 59.4000 -g 10.6000 -r 0
--------
Welcome to xflux (f.lux for X)
This will only work if you're running X on console.

Found 1 screen.
Display 1 has 0 size
Sorry, we only support 8, 10, 11, and 12-bit displays right now.
 `
FYI, i had it working on the same computer on 16.04.
It's just an i7-7500U.

**Comment by ntc2** [comment]
@izznogooood, yeah, see that part about "we only support <blah>-bit displays"? That's Issue #27 alright. And I assume the `xflux12` you used is the new version linked to in Issue #27? If "yes", you should comment on the corresponding issue at the flux web site and let them know the new binary does not work for you: https://forum.justgetflux.com/topic/2373/sorry-we-only-support-8-and-10-bit-displays-right-now/40.

Closing as duplicate; thanks for investigating!
