### ISSUE TITLE
Screen colors revert to normal after 10 seconds on Linux Mint 18.1

### ISSUE THREAD

**Issue by HipeL** [xflux-gui/xflux-gui#59]
As I run f.lux indicator my screen colors do go down, and if i do a preview it does turn on but.. after X seconds (not the preview, the actual applet) stops working. I need to pause and unpause wich isn't really something that is ok to do every 10 seconds or so...
Linux Mint 18.1

**Comment by ntc2** [comment]
Can you make sure you don't have multiple copies of the `xflux` program
running at the same time? Try doing `pgrep xflux` while you're experiencing
the problem.

**Comment by ntc2** [comment]
Haven't heard anything back, so going to assume this resolved itself.

**Comment by HipeL** [comment]
DIdn't saw the notification, sorry for huge delay. Actually, i tried a bunch of solutions and even went as far as trying in a different machine (same OS and such from coworker computer) and same kept happening, I can try and help you debug by doing some tests that you need but my solution was to use a different software. Thanks anyways for the help :)

**Comment by ntc2** [comment]
So, you tried it on another machine it had the same problem. That's a good test.

How did you install `fluxgui`?

What if you run `xflux` directly from the command line, does that work? You can run it like this:
```
xflux -l <latitude> -g <longitude> -k 2500 -nofork
```
But you'll need to choose `<latitude>` and `<longitude>` values for somewhere that it's night time.

**Comment by HipeL** [comment]
Same happens, screen goes into the set temperature and after some seconds goes back to normal, even though I can still find the process open.
I followed the github installing process, there really wasn't much science to it.

**Comment by ntc2** [comment]
Thanks for testing that. Sounds like this is an upstream problem with `xflux`. You could try repeating the "run `xflux` manually" experiment with this unofficial version of `xflux` and see if you have the same problem: https://justgetflux.com/linux/xflux12.tgz.

**Comment by tomtobac** [comment]
same problem on elementary OS 0.4 Loki.
I tried with with the unofficial version, doesnt work...
```
Welcome to xflux (f.lux for X)
This will only work if you're running X on console.

Found 1 screen.
Your location (lat, long) is 39.7, 2.9

Your night-time color temperature is 2500

```

**Comment by ntc2** [comment]
@tomtobac , thanks for confirming the problem with the `xflux12` version! Looks like this is an upstream problem that we can't address here (the `fluxgui` project just maintains the GUI; @herf maintains the `xflux` program itself), so closing as "won't fix".
