### ISSUE TITLE
How to install

### ISSUE THREAD

**Issue by dvorapa** [xflux-gui/xflux-gui#6]
Add information about how could we install f.lux from here (setup.py makes nothing on Ubuntu 16.04)

**Comment by castillobg** [comment]
:+1:

**Comment by Zranz** [comment]
`sudo apt install python-appindicator python-xdg`
`sudo python ./setup.py install`

**Comment by dvrein** [comment]
One liner bash script to download & install fluxgui (on Ubuntu 16.04 Xenial)

``` sh
sudo apt-get install git python-appindicator python-xdg python-pexpect python-gconf python-gtk2 python-glade2 -y
cd ~/Downloads
git clone "https://github.com/xflux-gui/xflux-gui.git"
cd xflux-gui
sudo python ./setup.py install
```

**Comment by castillobg** [comment]
@ghost Thanks! That worked for me.

**Comment by dvrein** [comment]
Hi, I'm the @ghost. I deleted my account because I got some issues with my account. I'm happy the simple script  working for you guys.  :smiley: 

You also can use `xflux -l <latitude>` in Terminal and you're done for quick setup without launching the GUI. Thanks to the dev for bringing this software to open source community and made it compatible with Linux. :)

> I also forgot that the GUI already have the geo position search. You also can use that as an alternative.

**Comment by hyarinx** [comment]
I take the commands into gist, in case anyone need references in the future.

https://gist.github.com/hyarinx/0877f04a9d932d5c15382eb53e8a3ae2

**Comment by dvrein** [comment]
Solution worked. :smile:

**Comment by andrewregan** [comment]
I created a pull request to update the readme with install instructions

#11

**Comment by ntc2** [comment]
@dvorapa: I just merged @andrewregan documentation patch. Can you try it and check that it works for you, and then close this ticket if "yes"?

**Comment by dvorapa** [comment]
I don't know, I installed it by installing dependencies listed in debian/control right after I created this issue (without ia32-libs, they were not needed and everything works as expected without them on 64bit). But I think it should work.

**Comment by skelic2** [comment]
@dvorapa I think ia32-libs is for 64 bit arch that doesn't have 32 bit libs for the program by default.

**Comment by dvorapa** [comment]
@skelic2 Even if the program is compiled for 64bit? I don't know

**Comment by skelic2** [comment]
compiled? Probably you don't need ia32-libs to be preinstalled in end user system, *if* you're compiling (im using C/C++ for this case), the program as static binary.
