### ISSUE TITLE
Ubuntu/Debian Manual Install (intruductions) - need to be updated

### ISSUE THREAD

**Issue by lukashanak** [xflux-gui/xflux-gui#60]
"cd xflux-gui" doesn't work, it have to be "cd xflux-gui-master"..

I know, it's a small isue, but I think it should be updated :D

**Comment by ntc2** [comment]
@lukashanak, the name of the repo depends on how you clone it. The name `xflux-gui` is the default name you get when running
```
git clone git@github.com:xflux-gui/xflux-gui.git
```
which is the way I expect most users are cloning the repo. Do you know how you cloned it, that made you end up with a repo called `xflux-gui-master`?
