### ISSUE TITLE
Make it have features like Windows app v4.30+

### ISSUE THREAD

**Issue by VladimirDev93** [xflux-gui/xflux-gui#62]
Hey, me again 😃

I was wondering, would it be possible that the f.lux app gets an update just like the one on Windows? That Windows app is super good, has all kinds of features and color temperatures from 6500K to 1200K (I use 1900K, but I don't have that on Ubuntu!) 
This v4.33 version has stuff like "Darkroom" , "Emerald Light", "Vignette Mode", etc. and all of these features are really cool and I would like to see that on f.lux app for Ubuntu, if it's possible.
Also, the f.lux app for Ubuntu says "Year 2010".

**Comment by ntc2** [comment]
Hi!

This project is only the GUI for the Linux `xflux` application. The `xflux` application is developed by @herf. Except for the available color temps, I think you're other requests are unfortunately out of scope for `fluxgui`. 

Regarding the color temps, the 2000K is the lowest color temp supported by `xflux`; see https://github.com/xflux-gui/xflux-gui/commit/be3be68c2f27c0cb9fc02368752ae4d3028395c1. I don't know why lower temps are not supported -- I think they were in the past -- but @herf may know. It would be possible for `fluxgui` to add more available temps above 2000K; the current list is hard coded here: https://github.com/xflux-gui/xflux-gui/blob/be3be68c2f27c0cb9fc02368752ae4d3028395c1/src/fluxgui/settings.py#L15.

You might consider using RedShift instead: it's open source, unlike `xflux`, and seems to be actively developed. It has a GUI, and is also easy to use from the command line. It has some features that `xflux` lacks, like setting daytime temps in addition to nighttime temps.

**Comment by ntc2** [comment]
I'm going to close this as "won't fix", but if you would like there to be more available color temps *above* 2000K, please create a separate issue for that.

**Comment by Sylk** [comment]
Shame, I really wanted the emerald city as I use that when I have intense migraines.
