### ISSUE TITLE
doesn't work on Ubuntu17.04

### ISSUE THREAD

**Issue by leodaft** [xflux-gui/xflux-gui#63]
when i updated my o.s. from Ubuntu 16.10 to Ubuntu17.04 f.lux stop working. I tried to reinstall it but nothing has been changed.

**Comment by ntc2** [comment]
Are you perhaps experiencing Issue #27? (See also Issue #58).

**Comment by leodaft** [comment]
yes, sorry

**Comment by ntc2** [comment]
No worries. Sorry that the `xflux` developers don't fix that issue!
