### ISSUE TITLE
Flux not working on debian 9

### ISSUE THREAD

**Issue by iamjosejimenez** [xflux-gui/xflux-gui#64]
Hi!

After upgrading my machine to debian 9 from debian 8 flux stopped working. I reinstalled the package using the same instructions as when I installed it the first time but It's still not working.

Thank you very much.

**Comment by ntc2** [comment]
Hey, how is it not working? E.g., does the `fluxgui` app fail to start? Does it start, but the options menus don't work? Does it it start and the GUI works, but the screen color doesn't change? Please describe your problem.

Are you perhaps experiencing one of these issues: #61 or #27?

**Comment by iamjosejimenez** [comment]
Thanks for taking the time to answer me. Yes, I'm having the same problem as #61. The program starts and the icon appears in the panel, I even changed the main options but the screen doesn't change its color.

**Comment by ntc2** [comment]
OK, so you're also getting an error about "signal 'child-added' is invalid"? If "yes", please close this issue and add a comment on #61 saying which OS you're using, and anything else you think might help (the other two people were using Debian 8 I think).
