### ISSUE TITLE
Often found spinning CPU, needing -9 to kill

### ISSUE THREAD

**Issue by kermit4** [xflux-gui/xflux-gui#73]
Linux e6400 4.4.0-93-generic #116-Ubuntu SMP Fri Aug 11 21:17:51 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
DISTRIB_DESCRIPTION="Ubuntu 16.04.3 LTS"

**Comment by faraco** [comment]
The description is vague. May you supply more details on this issue?
