### ISSUE TITLE
Cannot install on ubuntu 16.4 .

### ISSUE THREAD

**Issue by NikosEfthias** [xflux-gui/xflux-gui#8]
ppa:kilian/f.lux is down so i cannot install through package manager and when i try to install from the source code i get following error ![](http://i.imgur.com/P7juCzB.png)

**Comment by Zhiwei1996** [comment]
I have the same problem before, something wrong with git clone, have no xflux64 in dircetory /xflux-gui, I git clone again, sloved this problem perfectly
