### ISSUE TITLE
Xflux vs inverted colors

### ISSUE THREAD

**Issue by Yamakaky** [xflux-gui/xflux-gui#81]
Flux doesn't play way when the colors of the screen are inverted. When Flux changes the color profile, the screen is reset to a non-inverted state (does it make sense).

I use https://github.com/zoltanp/xrandr-invert-colors, but it seems to be a problem with xrandr.

Maybe before changing the color profile, you should check and maintain the invertedness?

**Comment by ntc2** [comment]
This sounds like an `xflux` feature, not a `fluxgui` feature, so closing.

**Comment by Yamakaky** [comment]
Oh, sorry

**Comment by ntc2** [comment]
You could submit a feature request to `xflux`. Perhaps in the forum: https://forum.justgetflux.com/category/7/linux.
